blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://shandley.github.io/ICTV-git/
    about: Please read the documentation first
  - name: Discussions
    url: https://github.com/shandley/ICTV-git/discussions
    about: For general discussions and community support
  - name: ICTV Official Site
    url: https://ictv.global
    about: For questions about ICTV taxonomy itself