name: Mark stale issues and PRs

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        
        # Issue configuration
        stale-issue-message: |
          👋 This issue has been automatically marked as stale because it has not had recent activity. 
          
          It will be closed in 14 days if no further activity occurs. To keep this issue open:
          - Add a comment with more information
          - Add the `keep-open` label
          - Submit a pull request referencing this issue
          
          Thank you for your contributions to ICTV-git! 🧬
          
        close-issue-message: |
          This issue was closed because it has been stalled for 14 days with no activity.
          
          If this issue is still relevant:
          - You can reopen it
          - Create a new issue referencing this one
          - Join our discussions for general questions
          
        stale-issue-label: 'stale'
        close-issue-label: 'closed-stale'
        exempt-issue-labels: 'keep-open,pinned,security,bug,in-progress,help-wanted,good-first-issue'
        days-before-issue-stale: 60
        days-before-issue-close: 14
        
        # PR configuration
        stale-pr-message: |
          👋 This pull request has been automatically marked as stale because it has not had recent activity.
          
          It will be closed in 14 days if no further activity occurs. To keep this PR open:
          - Push new commits
          - Add a comment with status update
          - Request a review
          - Add the `keep-open` label
          
          Thank you for your contributions to ICTV-git! 🧬
          
        close-pr-message: |
          This pull request was closed because it has been stalled for 14 days with no activity.
          
          If you'd like to continue working on this:
          - You can reopen this PR
          - Create a new PR with your changes
          - Reach out if you need help completing the work
          
        stale-pr-label: 'stale'
        close-pr-label: 'closed-stale'
        exempt-pr-labels: 'keep-open,pinned,security,in-progress,awaiting-review,dependencies'
        days-before-pr-stale: 30
        days-before-pr-close: 14
        
        # Operation options
        operations-per-run: 30
        remove-stale-when-updated: true
        debug-only: false
        
        # Exempt items
        exempt-all-assignees: false
        exempt-all-milestones: false
        
        # Don't mark issues/PRs stale if they have these labels
        exempt-draft-pr: true
        
        # Additional messages
        only-labels: ''
        any-of-labels: ''
        
        # Sorting
        ascending: false
        
        # Specific exemptions for research/data issues
        exempt-issue-labels: 'research,data-analysis,msl-parsing,documentation'
        exempt-pr-labels: 'research,visualization,msl-update'